# Generated by Django 4.2.5 on 2023-09-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pizzeria.order')),
                ('pizza_base', models.CharField(max_length=50)),
                ('cheese', models.CharField(max_length=50)),
                ('order_placing_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('toppings', models.ManyToManyField(to='pizzeria.toppings')),
            ],
        ),
    ]
