# Generated by Django 4.2.5 on 2023-09-05 06:39

from django.db import migrations, models
import django.db.models.deletion
import pizzeria.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_placing_time',
            field=models.DateTimeField(default=pizzeria.models.set_default_order_placing_time),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Accepted', max_length=20),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.order'),
        ),
    ]
