# Generated by Django 4.2.5 on 2023-09-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_orderitem_order_order_placing_time_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzabase', models.CharField(max_length=50)),
                ('cheese', models.CharField(max_length=50)),
                ('toppings', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzeria.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
